### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by rcj60560** [wenwenwen888/PullLoadMoreView#3]
想问下这种布局 是不是必须在最外层 里面的话嵌套一个滚动列表 都是可以的

**Comment by wenwenwen888** [comment]
应该可以，建议自行测试

**Comment by rcj60560** [comment]
@wenwenwen888 你好 我尝试在内容区域设置recyclerview 但是感觉滑动不是很顺滑，有时候会出现top_layhout 固定在上面动不了下面recyclcerview还能滑动的情况。

**Comment by wenwenwen888** [comment]
可以尝试修改触摸机制
